export const GET_BANKS_REQUEST = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS';
export const GET_BANKS_ERROR = 'GET_BANKS_ERROR';

export const AUTH_CARD_REQUEST = 'AUTH_CARD_REQUEST';
export const AUTH_CARD_SUCCESS = 'AUTH_CARD_SUCCESS';
export const AUTH_CARD_ERROR = 'AUTH_CARD_ERROR';

export const SAVE_CARD_REQUEST = 'SAVE_CARD_REQUEST';
export const SAVE_CARD_SUCCESS = 'SAVE_CARD_SUCCESS';
export const SAVE_CARD_ERROR = 'SAVE_CARD_ERROR';

export const RESET_AUTHED_CARD = 'RESET_AUTHED_CARD';
